name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload the built project artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: minecraft-ms-authenticator
          # A file, directory or wildcard pattern that describes what to upload
          path: amcc-app/target/*.jar
          
